name: Run Weather Alert

# Controls when the workflow will run
on:
  schedule:
    # 10pm EST from May through September
    - cron: '0 22 * 5-9 *'
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check-weather:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5' # install the python version needed
          
      - name: install python packages
        run: bash install.sh
        
      - name:  execute py script
        env: 
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python alert.py
